### ISSUE TITLE
LP : Reference lines to help cursor positionning

### ISSUE THREAD

**Issue by Maxew42** [surfriderfoundationeurope/labelcv-web#110]
Add two vertical and horizontal lines centered on the cursor when hovering the `AnnotationSurface` component that will help to position the the bounding box accurately ( just like in the `ZoomPanel` component )

**Comment by AntoineBruge** [comment]
Hello @Maxew42 

Merci pour la création de cette issue.
[La branche Develop](https://github.com/surfriderfoundationeurope/labelcv-web) est à jour. Tu peux travailler à partir de celle-ci.

Voici le process : 
1. Fork le repo sur ton compte (ce que tu as déjà fait)
2. Réalise les modifs
3. Crée une PR sur la branche develop
4. Tag @Vincent-Guiberteau @bertrandlalo et @jeanremy pour review

Je reste dispo si besoin :)
