### ISSUE TITLE
First request made to late

### ISSUE THREAD

**Issue by bertrandlalo** [surfriderfoundationeurope/labelcv-web#33]
https://github.com/surfriderfoundationeurope/labelcv-web/blob/78de498b2af265e72c6237fcf17646e451e0d5dd/src/views/Annotate.vue#L131-L144

First fetchState does not work.

**Comment by Vincent-Guiberteau** [comment]
Maybe we should copy/paste this part into the App.vue file at the higher level to launch this request at the begining no ?
