### ISSUE TITLE
Bounding box numbering bug

### ISSUE THREAD

**Issue by AntoineBruge** [surfriderfoundationeurope/labelcv-web#53]
When I add two bounding boxes on an image, and then delete one, the counter in the "validate" button at the bottom right is not updated!

This is probably related to the fact that there is a number on each bounding box (top left of each bounding box) and that the first bounding box is numbered "0"

![image](https://user-images.githubusercontent.com/46377579/104699806-90301f00-5713-11eb-9f1d-4151d61e4dd6.png)

**Comment by jules-larue** [comment]
I couldn't reproduce the bug neither on DEV nor PROD. Could you lprovide the detailed scenario that you used to get the bug (category assigned for each bounding box, which bounding box was removed (0 or 1) ...)
Thanks in advance ;)

**Comment by AntoineBruge** [comment]
I drawed 3 bounding boxes on https://www.trashroulette.com/#/, then deleted two of them and finally I added new bounding boxes ! 
I think the issue happen when you delete bounding boxes !
@jules-larue

**Comment by jules-larue** [comment]
Ok, it seems that issues is happening when you assign a category for bounding boxes, not when you don't assign categories.
