### ISSUE TITLE
Label with fragment id equals -1 and not 1

### ISSUE THREAD

**Issue by Vincent-Guiberteau** [surfriderfoundationeurope/labelcv-web#56]
When validating a new label with **fragments**, ids into database are registered in "-1" and not "1" 

https://github.com/surfriderfoundationeurope/labelcv-web/blob/087d396cf84e53cd3cbdaa18da270f04e7918514/src/components/annotation/AnnotationSurface.vue#L16

https://github.com/surfriderfoundationeurope/labelcv-web/blob/087d396cf84e53cd3cbdaa18da270f04e7918514/src/store/store.annotation.ts#L370

@bertrandlalo

**Comment by bertrandlalo** [comment]
J'arrive pas à lancer avec le vrai back, mais je crois que ce commit devrait fixer le problème : 
https://github.com/surfriderfoundationeurope/labelcv-web/commit/42fbfd3c7d990392e185bd25c33dabb7990bb0b8
A tester ! :)

**Comment by AntoineBruge** [comment]
Hello @bertrandlalo

J'ai tout cassé mais je tiens d'abord à dire que c'est de la faute de @Vincent-Guiberteau :)
J'ai voulu tester l'ajout d'une catégorie -> tire
J'ai donc modifié la table _trashtype_ du schéma _campaign_
![image](https://user-images.githubusercontent.com/46377579/107065122-b447c300-67dc-11eb-90c9-9493179e52d7.png)

Cette nouvelle catégorie est bien visible sur trashroulette
![image](https://user-images.githubusercontent.com/46377579/107065253-d6414580-67dc-11eb-9035-fe2898b4c63b.png)

Mais un -1 apparait de nouveau dans la DB après une labélisation correspondant à un "tire"
![image](https://user-images.githubusercontent.com/46377579/107065399-02f55d00-67dd-11eb-91a4-537a414b492a.png)

Qu'en pensez-vous?
Dans un futur proche, nous aimerions ajouter environ 10 catégories
:)

**Comment by bertrandlalo** [comment]
Hello Antoine !
C'est pas de ta faute, c'est le même bug que tu avais remonté dans l'issue
#56 !
Normalement ça
<https://github.com/surfriderfoundationeurope/labelcv-web/pull/57> devrait
le fixer !  Là tu testes sur quoi ? Pcq si @Vincent
<guiberteau.vincent@gmail.com> accepte la PR sur dev, on peut regarder si
ça le fait ?
Je suis dispo pour un petit appel tous les 3 entre midi et deux ou après
18h ! :)

**Comment by AntoineBruge** [comment]
Ca marche @Vincent-Guiberteau @bertrandlalo  !!! Vous êtes des machines :)
Merci !
