### ISSUE TITLE
Pictures appear on trashroulette whatever their orientation

### ISSUE THREAD

**Issue by AntoineBruge** [surfriderfoundationeurope/labelcv-web#59]
After a long discussion with @mchagneux , we decided to not crop pictures prior labeling.

Therefore, we would like to be able to label pictures on trashroulette independently of their orientation (portrait or landscape) and size.

Right now, pictures in portrait format are crushed. We would like to avoid that!

Any idea on how to do that @Vincent-Guiberteau @bertrandlalo @jules-larue @aaadryyy ? :)

![image](https://user-images.githubusercontent.com/46377579/107226517-86e85880-6a1a-11eb-9e39-b770d353087a.png)

**Comment by jules-larue** [comment]
Right now, the image is displayed as background of the left element, which is a `<div>`. Would you like the image to always have the same height and resize it preserving ratio? Or would you like the image to preserve current width and incrrease height to preserve ratio?
