### ISSUE TITLE
Add labelling decision tree

### ISSUE THREAD

**Issue by AntoineBruge** [surfriderfoundationeurope/labelcv-web#67]
Hello @jules-larue 

J'ajoute également cette seconde issue. L'idée est de faire en sorte que l'arbre de décision pour la labélisation soit toujours sous le nez des personnes qui labélisent. Ca leur permettra d'être plus précis et de s'y référer dès que nécessaire.

Merci :)
![image](https://user-images.githubusercontent.com/46377579/108515789-c0944b80-72c5-11eb-80a2-a0224e4ed36c.png)

**Comment by jules-larue** [comment]
Pour ce schéma, je propose de le rendre un peu plus lisible en ajoutant des images / icones au dessus de chaque libellé de trashtype enfant (pas les catégories donc), qu'en penses-tu ?

**Comment by AntoineBruge** [comment]
Salut @jules-larue ,

Oui bonne idée, je peux te mettre à dispo des photos ou des icones! Tu n'as pas peur que le schéma soit trop grand à la fin?
